import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

export default function DisclaimerPage() {
  return (
    <div className="container mx-auto py-8">
      <h1 className="text-4xl font-bold tracking-tight mb-2">Disclaimer</h1>
      <p className="text-xl text-muted-foreground mb-8">Important information about using our service</p>

      <Card>
        <CardHeader>
          <CardTitle>Disclaimer</CardTitle>
          <CardDescription>Last updated: {new Date().toLocaleDateString()}</CardDescription>
        </CardHeader>
        <CardContent className="prose dark:prose-invert max-w-none">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By using the Together AI Image Generator, you acknowledge that you have read, understood, and agree to be
            bound by this disclaimer. If you do not agree with any part of this disclaimer, please do not use our
            service.
          </p>

          <h2>2. Generated Content</h2>
          <p>
            The images generated by our service are created using artificial intelligence. While we strive to provide
            high-quality results, we cannot guarantee that the generated images will meet your specific requirements or
            expectations.
          </p>
          <p>
            You are solely responsible for the prompts you provide and the images that are generated as a result. We do
            not review or moderate the content of the prompts or the generated images.
          </p>

          <h2>3. Intellectual Property</h2>
          <p>
            The intellectual property rights for images generated using our service are subject to the terms of the
            Together AI model used (FLUX.1-schnell-Free). Please refer to Together AI's terms of service for more
            information on the usage rights for generated content.
          </p>
          <p>
            You are responsible for ensuring that your use of the generated images complies with all applicable laws and
            regulations, including copyright and intellectual property laws.
          </p>

          <h2>4. Prohibited Use</h2>
          <p>
            You agree not to use our service to generate content that is illegal, harmful, threatening, abusive,
            harassing, tortious, defamatory, vulgar, obscene, libelous, invasive of another's privacy, hateful, or
            racially, ethnically, or otherwise objectionable.
          </p>

          <h2>5. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special,
            consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or
            indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from:
          </p>
          <ul>
            <li>Your use or inability to use our service</li>
            <li>Any unauthorized access to or use of our servers and/or any personal information stored therein</li>
            <li>Any interruption or cessation of transmission to or from our service</li>
            <li>Any bugs, viruses, trojan horses, or the like that may be transmitted to or through our service</li>
          </ul>

          <h2>6. Changes to This Disclaimer</h2>
          <p>
            We reserve the right to modify this disclaimer at any time. We will notify you of any changes by posting the
            new disclaimer on this page.
          </p>

          <h2>7. Contact Us</h2>
          <p>
            If you have any questions about this disclaimer, please contact us at:
            <br />
            <a href="mailto:Usamariaz558@gmail.com" className="text-primary hover:underline">
              Usamariaz558@gmail.com
            </a>
          </p>
        </CardContent>
      </Card>
    </div>
  )
}
